### ISSUE TITLE
Virtual display gets deleted after closing and reopening laptop flap for 5 minutes

### ISSUE THREAD

**Issue by prakyath-07** [nomi-san/parsec-vdd#40] opened 2024-05-21 14:34 UTC
When the laptop flap is closed and then reopened after more than 5 minutes, the virtual display is deleted and needs to be reconfigured.

Im using [ParsecVDisplay-v0.45-setup.exe](https://github.com/nomi-san/parsec-vdd/releases/download/v0.45.1/ParsecVDisplay-v0.45-setup.exe) 

**Repro Steps:**

- Create virtual displays
- Close the laptop flap.
- Wait for more than 5 minutes.
- Reopen the laptop flap.
- Observe that the virtual display is deleted.

![System Info](https://github.com/nomi-san/parsec-vdd/assets/57027256/5f0c812e-880a-4e31-ac00-539649a64b4f)

**Comment by nomi-san** [comment] 2024-05-21 14:46
Have you disabled the "fast startup" options?

Never saw this case before but seems the app is stopped for a second before your laptop goes sleep, then all displays should be removed even the app is still opening. The next patch will restore your displays.

**Comment by prakyath-07** [comment] 2024-05-21 15:24
Yes , "fast startup" was enabled, I tried disabling it still facing the same issue

**Comment by prakyath-07** [comment] 2024-05-21 15:27
Do you have any immediate solution that I can try at my end?

**Comment by nomi-san** [comment] 2024-05-21 15:57
I have just tested 2 app versions. Sure the current implementation in WPF will stop all thread before sleeping. The old app in Winforms works properly, all displays are reserved. I will fix that soon.

Here is the old impl (no GUI, only has the context menu), lets try it.
[SimpleVDD.zip](https://github.com/nomi-san/parsec-vdd/files/15392385/SimpleVDD.zip)

**Comment by prakyath-07** [comment] 2024-05-22 05:39
Could you please provide the driver files for the same?

**Comment by nomi-san** [comment] 2024-05-22 05:50
I used the latest v0.45

**Comment by prakyath-07** [comment] 2024-05-22 06:05
I tried with [SimpleVDD](https://github.com/nomi-san/parsec-vdd/files/15392385/SimpleVDD.zip) its still same. Virtual display is getting deleted 

Devices Tested On  :
- Asus TUF F15
- Dell Precision 5540

**Comment by prakyath-07** [comment] 2024-05-28 11:17
Any updates?

**Comment by nomi-san** [comment] 2024-06-05 21:16
Im not sure your laptop was going sleep (suspended) or hibernated when closing lid. But sure that the app suspended a few seconds after getting up. I have tested on many latop devices with both Sleep mode and Hibernate mode, that give the same behaviours. And the SimpleVDD works as well, so the next patch I will apply these fixes from the old approach.

**Comment by nomi-san** [comment] 2024-06-07 10:45
Reopened because sometimes these fixes will not work as expected, the app is not a windows service, so it resumes too late after booting. There's a fork can solve your issue: https://github.com/timminator/ParsecVDA-Always-Connected

**Comment by nomi-san** [comment] 2024-12-30 23:42
In summary, the issue is caused by the old threading model. When adding or removing a virtual display, the app got stuck a second, the update timer also stopped working then all virtual displays got removed.

Closed as completed.

**Closed by nomi-san** 2024-12-30 23:42 UTC
Labels: bug
